### ISSUE TITLE
Twitch returning "error: (403) Forbidden"

### ISSUE THREAD

**Issue by Pritesh1G** [Ezzpify/ClipToTube#5]
I managed to set it up and when I run it it adds the URLS sucessfully from the subreddit but while downloading I'm facing this issue.

 `Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
Weberror at DownloadFile System.Net.WebException: The remote server returned an
error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ClipToTube.Web.DownloadFile(String url) in C:\Users\Abc\Desktop\work\LiveS
treamClips\ClipToTube\ClipToTube\ClipToTube\Web.cs:line 53
`

**Comment by Danny13653** [comment]
Also happening to me

**Comment by siriate** [comment]
+++

**Comment by Pritesh1G** [comment]
Did anyone manage to fix this issue?

**Comment by Djolezor** [comment]
Any fix??

**Comment by Pritesh1G** [comment]
Don't think the developer is supporting it anymore, I messaged him on Reddit as well with no response.

**Comment by Djolezor** [comment]
Oh man :C I spent the whole day messing with reddit login and youtube errors, finally got it to work and got this error.. I hate my life lul

**Comment by EqualOwl** [comment]
yea im guessing its something to do with the API

**Comment by Djolezor** [comment]
...RIP my spent time xD Im still trying but I think that must be fixed by developer/cant be fixed ;/

**Comment by Pritesh1G** [comment]
Yes, I spent a day as well to make this running, but I think the error has to do with something Twitch updated on their end.

**Comment by swiftyspiffy** [comment]
@Pritesh1G @EqualOwl @siriate @Djolezor 

See PR I just made, fixes the problem. #6
